# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-04 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorinfo', '0002_auto_20181120_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='media/'),
        ),
    ]
