# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-22 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
