# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-22 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
