# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-26 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20181126_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='re_password',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
